#   This file contains the PUCCH configuration for the gNB to support 5MHz BW or 10MHz BS in TDD mode.

cell_cfg:
  pucch:
    resource_set_size: 7
    nof_cell_res_set_configs: 1
    f1_nof_cyclic_shifts: 1
    f1_enable_occ: true
    nof_cell_sr_res: 7
    nof_cell_csi_res: 7
