cu_up:
  f1u:
    socket:
      - 
        # Default socket. If the DRB's 5QI does not have a socket assigned,
        # this socket will be used. At least one default socket is required. 
        bind_addr: 127.0.3.1  # Address that the F1-U socket will bind to.
        #ext_addr: 8.8.8.8    # Address that is reported as the F1-U bind address.
                              # If empty, the real bind address is used.
        udp:
          max_rx_msgs: 256    # maximum packets read from the socket in a single syscall.
          pool_threshold: 0.9 # Pool occupancy threshold, after which packets are dropped.

      -
        # Socket used for a specific slice/5QI. This socket will be used if both the S-NSSAI
        # and the 5QI match. Slice differentiator is optional.
        sst: 1                # Slice/Service type.
        # sd: 1               # Slice differentiator is optional.
        five_qi: 9            # 5G QoS Identifier.
        bind_addr: 127.1.3.1  # Address that the F1-U socket will bind to.
        #ext_addr: 8.8.8.8    # Address that is reported as the F1-U bind address.
                              # If empty, the real bind address is used.
        udp:
          max_rx_msgs: 256    # maximum packets read from the socket in a single syscall.
          pool_threshold: 0.9 # Pool occupancy threshold, after which packets are dropped.
      - 
        # Socket used for a specific slice/5QI. This socket will be used if both the S-NSSAI
        # and the 5QI match. Slice differentiator is optional.
        sst: 1                # Slice/Service type.
        sd: 2                 # Slice differentiator.
        five_qi: 9            # 5G QoS Identifier.
        bind_addr: 127.1.3.2  # Address that the F1-U socket will bind to.
        #ext_addr: 8.8.8.8    # Address that is reported as the F1-U bind address.
                              # If empty, the real bind address is used.
        udp:
          max_rx_msgs: 256    # maximum packets read from the socket in a single syscall.
          pool_threshold: 0.9 # Pool occupancy threshold, after which packets are dropped.
