# Example configuration file for mobility.

cu_cp:
  mobility:
    # List of all cells known to the CU-CP, their configs (if not provided over F1) and their respective neighbor cells.
    cells:
      - nr_cell_id: 0x66C000          # For the default gnb_id=411 (gnb_id_bit_length=22), NR cell IDs start with 0x66C000 and increment for each cell of the DU.
        periodic_report_cfg_id: 1     # This will configure a periodical report config for the serving cell.
        ncells:                       # List of nr_cell_ids that are a neighbor of this serving cell.
          - nr_cell_id: 0x20
            report_configs: [ 2 ]
      - nr_cell_id: 0x20              # This cell is not managed by this CU-CP
        ncells:
            - nr_cell_id: 0x66C000
              report_configs: [ 2 ]
        # Must be present if values are not provided over F1.
        gnb_id_bit_length: 32
        pci: 1
        ssb_arfcn: 632628
        band: 78
        ssb_scs: 30
        ssb_period: 20
        ssb_offset: 0
        ssb_duration: 5

    # gNB uses this report config to dynamically build a measConfig sent to the UEs using the below values.
    report_configs:
      - report_cfg_id: 1
        report_type: periodical
        report_interval_ms: 1024
      - report_cfg_id: 2
        report_type: event_triggered
        a3_report_type: rsrp
        a3_offset_db: 6
        a3_hysteresis_db: 0
        a3_time_to_trigger_ms: 100
        report_interval_ms: 1024
